{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terra-mystica.fullname" . }}-backend
  labels:
    {{- include "terra-mystica.backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "terra-mystica.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terra-mystica.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.security.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.backend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DATABASE_URL
              value: {{ include "terra-mystica.database.url" . | quote }}
            - name: REDIS_URL
              value: {{ include "terra-mystica.redis.url" . | quote }}
            {{- if .Values.opensearch.external.enabled }}
            - name: OPENSEARCH_HOST
              value: {{ .Values.opensearch.external.host | quote }}
            - name: OPENSEARCH_PORT
              value: {{ .Values.opensearch.external.port | quote }}
            - name: OPENSEARCH_SCHEME
              value: {{ .Values.opensearch.external.scheme | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
{{- end }}