extends: default

rules:
  document-start: disable
  document-end: disable
  line-length:
    max: 120
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']