# Override file for development (CPU-only)
# This file is used automatically by docker-compose
version: '3.8'

services:
  backend:
    environment:
      - ENABLE_GPU=false

  celery-worker:
    environment:
      - ENABLE_GPU=false