# Override file for development without GPU
# Use: docker-compose -f docker-compose.yml -f docker-compose.override.yml up
version: '3.8'

services:
  backend:
    deploy:
      resources: {}
    environment:
      - ENABLE_GPU=false

  celery-worker:
    deploy:
      resources: {}
    environment:
      - ENABLE_GPU=false